# cfg db information
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=demo
quarkus.datasource.password=demo
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/demo

# starta Flyway migrationer auto
quarkus.flyway.migrate-at-start=true


#hibernate
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.schema-management.strategy=validate

