version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace   # live reload
    ports:
      - "8080:8080"    # nå appen från browser
